<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TetPee.Service</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TetPee.Repository\TetPee.Repository.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Abstraction\" />
    </ItemGroup>

</Project>
